# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=10),
        ),
    ]
