# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20181127_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
