# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-01 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import produtos.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=produtos.models.upload_image_path),
        ),
    ]
