# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-01 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_produto_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default='abc'),
            preserve_default=False,
        ),
    ]
